// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBcCnigP-F5co0HZTIAIGC-GEvI60Avs',
    appId: '1:1061549505864:web:abb7ebb2baccb9b155077d',
    messagingSenderId: '1061549505864',
    projectId: 'stylish-57371',
    authDomain: 'stylish-57371.firebaseapp.com',
    storageBucket: 'stylish-57371.firebasestorage.app',
    measurementId: 'G-53P1EL83Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKXPqr4CuWTvoLE7jBlgu1LAicWmGX_4',
    appId: '1:1061549505864:android:4cc462067b09203955077d',
    messagingSenderId: '1061549505864',
    projectId: 'stylish-57371',
    storageBucket: 'stylish-57371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaR_2C3KZRs63ATGOr7aGPhb9cC4kICE',
    appId: '1:1061549505864:ios:3caf95a44324ddce55077d',
    messagingSenderId: '1061549505864',
    projectId: 'stylish-57371',
    storageBucket: 'stylish-57371.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkaR_2C3KZRs63ATGOr7aGPhb9cC4kICE',
    appId: '1:1061549505864:ios:3caf95a44324ddce55077d',
    messagingSenderId: '1061549505864',
    projectId: 'stylish-57371',
    storageBucket: 'stylish-57371.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJBcCnigP-F5co0HZTIAIGC-GEvI60Avs',
    appId: '1:1061549505864:web:90099431d397dd8655077d',
    messagingSenderId: '1061549505864',
    projectId: 'stylish-57371',
    authDomain: 'stylish-57371.firebaseapp.com',
    storageBucket: 'stylish-57371.firebasestorage.app',
    measurementId: 'G-DZFL574ZGL',
  );
}
